config/routes.rb
Rails.application.routes.draw do
  root 'shortened_urls#new'
  
  resources :shortened_urls

end

app/models/shortened_url.rb
class ShortenedUrl < ActiveRecord::Base
  before_validation :url, presence: true
  validates_url :url, :schemes => ['ftp','https','http']
  validates :short_url, presence: true
  validates_uniqueness_of :url
  validates_uniqueness_of :short_url, message: 'please try again'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shortened_urls_controller.rb
require 'url_shortener'

class ShortenedUrlsController < ApplicationController
  before_action :set_shortened_url, only: [:show, :edit, :update, :destroy]

  def new
    @shortened_url = ShortenedUrl.new
  end

  def create
    @shortened_url = ShortenedUrl.new(shortened_url_params)
    @minify_url = UrlShortener::MinifyUrl.new(shortened_url_params[:url], request.base_url)
    @shortened_url.short_url = @minify_url.minify

    respond_to do |format|
      if @shortened_url.save
        format.html { redirect_to @shortened_url, notice: 'Shortened url was successfully created.' }
        format.json { render :show, status: :created, location: @shortened_url }
      elsif @shortened_url.errors[:url].include? 'has already been taken'
        @shortened_url = ShortenedUrl.find_by_url(shortened_url_params[:url]);
        format.html { redirect_to @shortened_url, notice: 'Shortened url was successfully created.' }
        format.json { render :show, status: :created, location: @shortened_url }      
      else
        format.html { render :new }
        format.json { render json: @shortened_url.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shortened_url
      @shortened_url = ShortenedUrl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shortened_url_params
      params.require(:shortened_url).permit(:url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortened_urls_helper.rb
module ShortenedUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortener</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="main-container" class="container-fluid">
    <div class="row">
       <div id="topbar" class="col-xs-12">
         <h1>URL Shortener</h1>
       <div>
    </div>
    <div class="row">
      <br/>
      <br/>
      <br/>
      <br/>
      <div id="content" class="col-xs-12">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/shortened_urls/_form.html.erb
<%= form_for(@shortened_url, :html => {'class' => 'form'}) do |f| %>
  <% if @shortened_url.errors.any? %>
    <div class="row">
      <div class="alert alert-danger col-sm-5">
        <div>
          <h4><%= pluralize(@shortened_url.errors.count, "error") %> prohibited this shortened_url from being saved:</h4>
          <ul>
            <% @shortened_url.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>
  <div class="row">
    <div class="form-group col-sm-6">
      <%= f.text_field :url, :class => 'form-control'%>
    </div>
  </div> 
  <%= f.submit :class => 'btn btn-primary col-sm-3'%>
<% end %>

app/views/shortened_urls/new.html.erb
<%= render 'form' %>

app/views/shortened_urls/show.html.erb
<table class="table col-xs-7">
 <tr>
   <th>Url:</th>
   <td><%= @shortened_url.url %></td>
 </tr>
 <tr>
   <th>Short url:</th>
   <td><%= link_to @shortened_url.short_url, @shortened_url.url, :target => '_blank' %></td>
 </tr>
</table>

<%= link_to 'Create Shortened url', new_shortened_url_path, class: 'btn btn-primary' %>